<?php

namespace App\Observers;

use App\Itemlog;
use App\Item;
use App\Transaction;
use App\Worktype;

class ItemlogObserver
{
    /**
     * Handle the itemlog "created" event.
     *
     * @param  \App\Itemlog  $itemlog
     * @return void
     */
    public function created(Itemlog $itemlog)
    {
        // lets save the qty of item, for each new record from itemlog when its created.
        $item = Item::find($itemlog->item_id);
        $item->qty = $item->qty + $itemlog->qty;
        $item->save();


        //get positive numbers of item logs qty, for transaction purpose.
        $itemlog->qty = abs($itemlog->qty);
        $worktype = Worktype::find($itemlog->worktype_id);

        $subtotal = $worktype->price * $itemlog->qty;

        $note = $worktype->name . " " . $item->name . " " . $itemlog->qty . " " . $item->unit_name;

        Transaction::create([
            'item_id' => $item->id,
            'client_id' => $item->client_id,

            // 'fee_ref_id' => $itemlog->id,
            // 'fee_ref_table_name' => "itemlogs",

            'ref_id' => $itemlog->id,
            'ref_table_name' => "itemlogs",

            'qty' => $itemlog->qty,
            'nominal' => $subtotal,

            'desc' => $note,
            'note' => "Autogenerated from system itemlog observer."
        ]);
    }

    /**
     * Handle the itemlog "updated" event.
     *
     * @param  \App\Itemlog  $itemlog
     * @return void
     */
    public function updated(Itemlog $itemlog)
    {
        //
    }

    /**
     * Handle the itemlog "deleted" event.
     *
     * @param  \App\Itemlog  $itemlog
     * @return void
     */
    public function deleted(Itemlog $itemlog)
    {
        //
    }

    /**
     * Handle the itemlog "restored" event.
     *
     * @param  \App\Itemlog  $itemlog
     * @return void
     */
    public function restored(Itemlog $itemlog)
    {
        //
    }

    /**
     * Handle the itemlog "force deleted" event.
     *
     * @param  \App\Itemlog  $itemlog
     * @return void
     */
    public function forceDeleted(Itemlog $itemlog)
    {
        //
    }
}
